# Predicting the Fish Weight

In [1]:
import pandas as pd  # importing python pandas libraries 

In [ ]:
# Importing the Fish csv file 

In [2]:
data=pd.read_csv(r"C:\Users\Gogula Vinay\Desktop\Innomatics labs\Data Science\Machine Learning\Fish.csv")
data.head()

Species  Weight  Length1  Length2  Length3   Height   Width
0   Bream   242.0     23.2     25.4     30.0  11.5200  4.0200
1   Bream   290.0     24.0     26.3     31.2  12.4800  4.3056
2   Bream   340.0     23.9     26.5     31.1  12.3778  4.6961
3   Bream   363.0     26.3     29.0     33.5  12.7300  4.4555
4   Bream   430.0     26.5     29.0     34.0  12.4440  5.1340

In [31]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 159 entries, 0 to 158
Data columns (total 7 columns):
 #   Column   Non-Null Count  Dtype  
---  ------   --------------  -----  
 0   Species  159 non-null    int32  
 1   Weight   159 non-null    float64
 2   Length1  159 non-null    float64
 3   Length2  159 non-null    float64
 4   Length3  159 non-null    float64
 5   Height   159 non-null    float64
 6   Width    159 non-null    float64
dtypes: float64(6), int32(1)
memory usage: 8.2 KB


In [ ]:
# there are no null values in our dataset 

In [3]:
data['Species'].value_counts() # Imbalance dataset

Perch        56
Bream        35
Roach        20
Pike         17
Smelt        14
Parkki       11
Whitefish     6
Name: Species, dtype: int64

In [ ]:
# Convering categorical data into vectors 

In [4]:
from sklearn.preprocessing import LabelEncoder
l=LabelEncoder()
data['Species']=l.fit_transform(data['Species'])

In [5]:
Species=pd.DataFrame(data[['Species']])
Species

Species
0          0
1          0
2          0
3          0
4          0
..       ...
154        5
155        5
156        5
157        5
158        5

[159 rows x 1 columns]

In [6]:
data

Species  Weight  Length1  Length2  Length3   Height   Width
0          0   242.0     23.2     25.4     30.0  11.5200  4.0200
1          0   290.0     24.0     26.3     31.2  12.4800  4.3056
2          0   340.0     23.9     26.5     31.1  12.3778  4.6961
3          0   363.0     26.3     29.0     33.5  12.7300  4.4555
4          0   430.0     26.5     29.0     34.0  12.4440  5.1340
..       ...     ...      ...      ...      ...      ...     ...
154        5    12.2     11.5     12.2     13.4   2.0904  1.3936
155        5    13.4     11.7     12.4     13.5   2.4300  1.2690
156        5    12.2     12.1     13.0     13.8   2.2770  1.2558
157        5    19.7     13.2     14.3     15.2   2.8728  2.0672
158        5    19.9     13.8     15.0     16.2   2.9322  1.8792

[159 rows x 7 columns]

In [ ]:
# Spliting the data into dependent and independent features.

In [7]:
cl=data[['Weight']]
fv=data[['Species','Length1','Length2','Length3','Height','Width']]

In [8]:
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(fv,cl,train_size=0.8)

In [ ]:
# Since the data is haveing significant difference in their scales,
# are needed to be modified in such a way that all those values fall into the same scale.

In [9]:
from sklearn.preprocessing import StandardScaler
std = StandardScaler()
transfromed_train = std.fit_transform(x_train)
transfromed_test = std.transform(x_test)

In [10]:
lr=LinearRegression()

In [11]:
model=lr.fit(transfromed_train,y_train)

In [12]:
# y=wx+wo

In [13]:
lr.get_params()

{'copy_X': True,
 'fit_intercept': True,
 'n_jobs': None,
 'normalize': 'deprecated',
 'positive': False}

In [14]:
predi=model.predict(transfromed_test)

In [15]:
from sklearn.metrics import mean_squared_error,mean_absolute_error,r2_score

In [16]:
mean_squared_error(y_test,predi)

12897.033684503422

In [17]:
mean_absolute_error(y_test,predi)

76.24790046243203

In [18]:
r2_score(y_test,predi)

0.9098749775155442

In [19]:
model.coef_

array([[  49.14326023,  409.1144155 ,  422.39166205, -623.58984053,
         203.72332454,  -12.45804551]])

In [20]:
model.intercept_

array([383.97480315])

In [26]:
import warnings 
warnings.filterwarnings('ignore')

In [27]:
len(model.predict(fv))

159

In [28]:
model.predict(fv).reshape(len(model.predict(fv)))

array([ 4193.29359855,  4344.44619191,  4424.68667628,  5040.67357198,
        4743.98388012,  4964.44641117,  5202.35909009,  5044.38440224,
        5252.05963671,  5273.7132605 ,  5365.09017692,  5513.55670459,
        5644.52467755,  5480.66726281,  5713.07175935,  5806.49452688,
        5838.05132779,  5730.23735187,  6226.01269464,  5961.01148692,
        5931.41704773,  6338.12688636,  6183.63088665,  5934.71318629,
        6201.98492355,  5930.19945834,  6199.00753951,  6381.13753975,
        6431.27561198,  6932.59460028,  7060.71942701,  7132.85192969,
        7366.34742233,  8092.54587803,  7762.40718247,  2528.31734659,
        3403.82460968,  3560.60536347,  3650.77376824,  4016.03139259,
        4072.29733215,  3989.65499805,  3813.15928807,  3952.16897542,
        4414.05831075,  4079.65695199,  4378.98172676,  4383.41709802,
        4243.97513202,  4178.75138612,  4291.45660002,  4876.80596856,
        4925.043554  ,  4817.16570519,  6079.19726917,  5073.45551517,
      

In [ ]:
# Saving the model

In [29]:
import joblib

In [30]:
joblib.dump(model,r'C:\Users\Gogula Vinay\Desktop\Innomatics labs\Data Science\Machine Learning\linear_regression_fish-scaling.joblib')

['C:\\Users\\Gogula Vinay\\Desktop\\Innomatics labs\\Data Science\\Machine Learning\\linear_regression_fish-scaling.joblib']